version: 0.2

env:
  variables:
    AWS_REGION: "eu-south-1"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Building the project
      - npm run build

  post_build:
    commands:
      - echo Running tests
      - npm test
      - echo Logging into CodeArtifact
      - aws codeartifact login --tool npm --repository deepscribes-dao --domain deepscribes --domain-owner 786914421882
      - echo Publishing package
      - npm publish

cache:
  paths:
    - node_modules
